### ISSUE TITLE
Feature request: interpolate vars

### ISSUE THREAD

**Issue by leegee** [iendeavor/import-meta-env#10]
Would it be in https://github.com/iendeavor/import-meta-env/blob/main/packages/shared/resolve-env.ts that I'd need to make adjustments to allow interpolation of env vars, something like the below?

```javascript
const dotenv = require('dotenv')
const dotenvExpand = require('dotenv-expand')
const findConfig = require("find-config");
const configPath = dotenv.config({ path: findConfig(".env") });

dotenvExpand.expand(configPath);
```

Then  I can have my `.env` use the value of an env var in other env vars, so `ENDPOINT_ONE=${SERVER_NAME}`, etc. Maybe then I could set `SERVER_NAME` on the command line, or at worst only one per `.env` file.

**Comment by iendeavor** [comment]
Since there are many ways to load environment variables, we only provide the most common way (that is, loading environment variables from `.env` file for local development).

If you need to disable the above behavior, you can set the `env` option to `""` to only use `process.env`.
