### ISSUE TITLE
BREAKING CHANGE - @import-meta-env/cli@0.6.5 not correctly parsing escape characters

### ISSUE THREAD

**Issue by Usuychik** [iendeavor/import-meta-env#1043]
In version 0.6.5 broken escape characters substitution

For example -- you have next one ENV var:
`VITE_TOKENS="[\"XXXX\",\"YYY\"]"`
And next script in index.html

<script>globalThis.import_meta_env = JSON.parse('\"import_meta_env_placeholder\"');</script>

command: ` import-meta-env -x .env.example -p index.html`
gives next result:
`<script>globalThis.import_meta_env = JSON.parse('{"VITE_TOKENS":"[\\\\\"XXXX\\\\\",\\\\\"YYY\\\\\"]"}');</script>`
And JSON parse fails.

on version 0.6.2 result is next and its working:
`<script>globalThis.import_meta_env = JSON.parse('{"VITE_TOKENS":"[\\\"XXXX\\\",\\\"YYY\\\"]"}');</script>`

**Comment by iendeavor** [comment]
Hi, @Usuychik 

Sorry about the inconvenience you are experiencing with this.

But since it is a different from the behavior of the compile-time transforming tools, we think it is a bug fixes.

Thank you for your feedback and understanding.
