### ISSUE TITLE
Using Docker setup with Vite

### ISSUE THREAD

**Issue by nvonbenken** [iendeavor/import-meta-env#125]
Does any of the configuration from the Vite examples need to be applied to access the variables loaded in through docker? I'm having issues obtaining the values in my Vite React app.

**Comment by nvonbenken** [comment]
Reproducible example: https://github.com/nvonbenken/vite-runtime-vars-docker

**Comment by iendeavor** [comment]
Hi @nvonbenken 

Sorry for that the examples' README.md is not updated😅.

Please refer to [this full example](https://iendeavor.github.io/import-meta-env/guide/getting-started/introduction.html#full-example) instead.

In addition, the entire object access (i.e., `import.meta.env`) is no longer supported in v0.3.0, you need to use `import.meta.env.TEST` to obtain your environment variable.

Thank you for your feedback😃.

**Comment by nvonbenken** [comment]
Looking over that I'm not really sure what I'm missing. Is it just this line in the `index.html`?

```
<script id="import-meta-env"></script>
```

**Comment by iendeavor** [comment]
Not only, you also need to:

1. install unplugin packages to do compile-time transform:

    ```sh
    $ npm i -D @import-meta-env/unplugin
    ```

2. add corresponding config for step 1:

    ```diff
    // vite.config.ts
    import { defineConfig } from 'vite'
    import react from '@vitejs/plugin-react'
    + import importMetaEnvPlugin from '@import-meta-env/unplugin'
    
    // https://vitejs.dev/config/
    export default defineConfig({
      plugins: [
        react(),
    +   importMetaEnvPlugin.vite({
    +     example: '.env.example.public'
    +   })
      ]
    })
    ```

3. update preview script in package.json:
    
    ```diff
    {
      "scripts":
    -   "preview": "vite preview"
    +   "preview": "import-meta-env --example .env.example.public && vite preview"
    ```

4. update `src/App.tsx`:

    ```diff
    - console.log(import.meta.env);
    + console.log(import.meta.env.TEST);
    ```
