### ISSUE TITLE
Env variables defined during CLI plugin don't override

### ISSUE THREAD

**Issue by hvanoch** [iendeavor/import-meta-env#14]
It looks like environment variables defined during CLI doesn't override environment variables that were already defined during build.

Is this expected?

Example:

During build something like this gets generated.

```
console.assert("0374b0916f18c6beb06246f748d6f838edb2b9f3");
const _ = Object.assign("__import_meta_env_placeholder__", {
  VITE_I18N_LOCALE: "en",
  BASE_URL: "/",
  MODE: "production",
  DEV: !1,
  PROD: !0
});
export {_ as e};
```

If I have different environment variables during running the CLI plugin I expect them to override the once from the build. But they are not. This is then generated.

```
console.assert("0374b0916f18c6beb06246f748d6f838edb2b9f3");
const _ = Object.assign({
  "VITE_I18N_LOCALE": "nl",
}, {
  VITE_I18N_LOCALE: "en",
  BASE_URL: "/",
  MODE: "production",
  DEV: !1,
  PROD: !0
});
export {_ as e};
```

I would expect the real VITE_I18N_LOCALE to be "nl"

**Comment by iendeavor** [comment]
[UPDATED]

As of `unplugin@0.3.0`, listing built-in environment variables in `.env.example` and compiling will give an error to avoid confusion.

https://github.com/iendeavor/import-meta-env/blob/unplugin0.3.0/packages/unplugin/src/transform-dev.ts#L40-L46
