### ISSUE TITLE
import_meta_env_unique_id_xxxxxxxx has already been declared

### ISSUE THREAD

**Issue by Vulthil** [iendeavor/import-meta-env#15]
When running vite build on my project, I keep getting the following error:
```
error during build:
Error: Identifier 'import_meta_env_unique_id_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' has already been declared (Note that you need plugins to import files that are not JavaScript)
    at error (file:///C:/project/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at Module.error (file:///C:/project/node_modules/rollup/dist/es/shared/rollup.js:12412:16)
    at Module.tryParse (file:///C:/project/node_modules/rollup/dist/es/shared/rollup.js:12789:25)
    at Module.setSource (file:///C:/project/node_modules/rollup/dist/es/shared/rollup.js:12694:24)
    at ModuleLoader.addModuleSource (file:///C:/project/node_modules/rollup/dist/es/shared/rollup.js:22136:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
My App.vue file is using the <script setup> syntax, which I can't find an example of in the examples, so it might not be supported ?

The regular 'vite' command for running the development server, works fine, except it stopped reacting to changes to the '.env' file, and keeps using the value from the intial startup, even though the process is reporting 
'[vite] .env changed, restarting server...'
'[vite] server restarted.'

My vite.config.ts looks like this:
```
import { defineConfig } from "vite";
import importMetaEnv from "@import-meta-env/unplugin";

export default defineConfig({
  plugins: [
    importMetaEnv.vite({ example: ".env.example.public" }),
  ],
});
```

Any thoughts on this ?

**Comment by Vulthil** [comment]
Interesting.

I'm using yarn `v.1.22.19`, but that should not break this.

**Comment by iendeavor** [comment]
What is the Node version you using?

**Comment by iendeavor** [comment]
I forked the repo and added CI to it: https://github.com/iendeavor/TestImportMetaEnv/actions/runs/3220255336

Could you try cleaning your local cache: https://yarnpkg.com/cli/cache/clean.

**Comment by Vulthil** [comment]
I've swapped computer for now, and there the repo works aswell (clean install).

I will try again at work tomorrow where I clean the yarn cache, but the docker builds fails aswell, and they should (hopefully) be clean. I have not included the Dockerfile in the repro repo as the error occured on the local build aswell.

It might have something to do with a private npm feed I'm using, but the packages get installed correctly, so I don't see why that should interfere with the build step.

**Comment by Vulthil** [comment]
> Maybe we need to dump log by setting `DEBUG_IMPORT_META_ENV=1` to environment variable and run `yarn run build > log` again.

A log file containing the output of the above command has been uploaded in the reproduction repo: https://github.com/Vulthil/TestImportMetaEnv

**Comment by iendeavor** [comment]
I'll create a reproducible example and fix it ASAP.

**Comment by iendeavor** [comment]
This issue is fixed, and release in [@import-meta-env/unplugin@0.1.10](https://github.com/iendeavor/import-meta-env/commit/22dc3483065adab61883162547520bb24b362836).

**Comment by Vulthil** [comment]
It looks fixed in the reproduction repo on my part aswell.
