### ISSUE TITLE
The document is too concise to understand how to use it.

### ISSUE THREAD

**Issue by liujianchao1995** [iendeavor/import-meta-env#185]

**Comment by iendeavor** [comment]
很抱歉，英文不是很好，可能詞不達意。

有哪些部分寫不完整的，我可以先用中文回覆您😅

**Comment by liujianchao1995** [comment]
> 很抱歉，英文不是很好，可能詞不達意。
> 
> 有哪些部分寫不完整的，我可以先用中文回覆您😅

我想在 vue3 + vite + docker + k8s 的项目中使用这个模块，编译后的前端程序可以获取k8s或docker run中动态传入的环境变量值吗？
具体应该怎么操作，项目中的示例无法正常启动，文档有点看不太懂。

如蒙赐教，不胜感激。

**Comment by iendeavor** [comment]
> 我想在 vue3 + vite + docker + k8s 的项目中使用这个模块，编译后的前端程序可以获取k8s或docker run中动态传入的环境变量值吗？

可以的！這個套件就是為此而生 😆 

> 具体应该怎么操作，项目中的示例无法正常启动，文档有点看不太懂。

1. 新增一個 `.env.example` 檔案，裡面填入你要使用環境變數（注意，以下說到環境變數都是指可以公開的變數，請勿填入含有密碼金鑰等資訊的變數名稱）

    ```ini
    NAME=
    ```

2. 如果是 vite + vue 3，你應該會有一個 `index.html`，你須要加入以下程式碼到 <body>，這段程式碼會在 docker 啟動時被轉譯

    ```html
    <script>globalThis.import_meta_env=JSON.parse('"import_meta_env_placeholder"')</script>
    ```

3. 在 JavaScript 中，用 `import.meta.env.NAME` 取得環境變數

4. Vite 的話可以使用這兩個套件搭配：
   - `@import-meta-env/unplugin` - 這個負責編譯時期的轉譯，安裝方式：https://iendeavor.github.io/import-meta-env/guide/getting-started/compile-time-transform.html#unplugin
   - `@import-meta-env/cli` - 這個負責執行時期的轉譯

5. 本地開發時，傳入環境變數並執行 `NAME=value npm run dev` 就可以了，此時只會使用 `@import-meta-env/unplugin` 進行轉譯

6. 正式環境時：
   a. 執行 `npm run build` ，此時會使用 `@import-meta-env/unplugin` 進行第一次轉譯
   b. Dockerfile 要順便將 `@import-meta-env/cli` 打包成你最終 docker 的環境，這邊以 alpine-linux 為例：https://github.com/iendeavor/import-meta-env/blob/main/packages/examples/docker-starter-example/Dockerfile#L13-L15
   c. Docker 的 進入點，需要改為腳本執行，因為我們需要在啟動的時候注入環境變數： https://github.com/iendeavor/import-meta-env/blob/main/packages/examples/docker-starter-example/start.sh#L5
   d. 都準備好後，執行 `docker run -e NAME=value <你的 image 名稱跟其他參數...>` 進行第二次轉譯，並啟動 app


另外，這邊有一個相當小的 Vite 的例子，雖然不含 docker ，但概念都是一樣的： https://github.com/iendeavor/import-meta-env/tree/main/packages/examples/vite-vanilla-example

如果遇到任何問題的話，再麻煩提供一個小的、可以重現的 repo，直接看程式碼會比較好除錯~謝謝您

**Comment by iendeavor** [comment]
Close for now, if you have any questions, please feel free to reopen, thank you.
