### ISSUE TITLE
How to use import.meta.env with cypress for e2e?

### ISSUE THREAD

**Issue by cmcleese** [iendeavor/import-meta-env#213]
When using env variables in my project js, for example:
`export const VITE_APP_WEBAPI = import.meta.env.VITE_APP_WEBAPI;`

And then running cypress test, it seems that it cannot understand import.meta
Cypress is bundling the files it seems with webpack but i guess ` import.meta.env` library needs to added as a plugin? 
Not sure...

Do you have an example on how to do it with cypress 11 ?

**Error**:
```
Error: Webpack Compilation Error
./src/services/environmentVariables.ts 1:37
Module parse failed: Unexpected token (1:37)
File was processed with these loaders:
 * C:\Users\[USER]\AppData\Local\Cypress\Cache\11.2.0\Cypress\resources\app\node_modules\@packages\server\node_modules\ts-loader\index.js
You may need an additional loader to handle the result of these loaders.
> export const VITE_APP_WEBAPI = import.meta.env.VITE_APP_WEBAPI;
| 
```

**Comment by cmcleese** [comment]
I tried this in `cypress.config.ts`

But it didn't work..

```js

export default defineConfig({
 ...
 e2e: {
    setupNodeEvents(on, config) {
      on(
        'file:preprocessor',
        webpackPreprocessor({
          webpackOptions: {
            plugins: [
              require('@import-meta-env/unplugin').webpack({
                example: '.env.example',
              }),
            ],
          },
          watchOptions: {},
        })
      );
      registerCodeCoverageTasks(on, config);
      return config;
    }
```

**Comment by iendeavor** [comment]
I created an [example](https://github.com/iendeavor/import-meta-env/tree/main/packages/examples/cypress-example) which follows the official Cypress document on [component](https://docs.cypress.io/guides/component-testing/react/quickstart) and [E2E](https://docs.cypress.io/guides/end-to-end-testing/testing-your-app#Step-3-Configure-Cypress) testing.

For E2E testing you will *visit* (`cy.visit(...)`) your devServer (e.g., `webpack-dev-server`), I don't think you need to add any configuration in `cypress.config.ts` because you already configured Import-meta-env in `webpack.config.js`.

Hope this helps you 😄 .

**Comment by cmcleese** [comment]
Sorry I should have clarified. 
I'm not using Webpack so I don't have `webpack.config.js` file.
I'm using **Vite**. 
However the error I was seeing was when running cypress , it would error and complain about `Error: Webpack Compilation Error` in my post above.

I have specified the` cypress.config` to use
```js
devServer: {
      framework: 'vue',
      bundler: 'vite',
    },
```
So it was strange to see this error about webpack.
I'm still not sure how to get this to work correctly.

**Comment by iendeavor** [comment]
Thank you for your clarification 😅.

Can you create a minimal repo to reproduce this? Maybe I can find out why it works like that.

**Comment by cmcleese** [comment]
Hi I solved the issue by not using `import.meta.env` in `cypress.commands` and instead use recommendation from there docs.
Solution here: https://github.com/cypress-io/cypress/issues/25187
