### ISSUE TITLE
TypeError: Object prototype may only be an Object or null: import_meta_env_placeholder

### ISSUE THREAD

**Issue by cmcleese** [iendeavor/import-meta-env#215]
When adding this to index.html before the document entrypoint:
```
<script>
      globalThis.import_meta_env = JSON.parse('"import_meta_env_placeholder"');
    </script>
```

After building with VITE and running the dist code, i receive the following error:
```
TypeError: Object prototype may only be an Object or null: import_meta_env_placeholder
```

![image](https://user-images.githubusercontent.com/2061466/208067045-d62e327b-15c1-4ca0-b846-3a58a3087fc9.png)

**Comment by iendeavor** [comment]
In production, the placeholder need to be transformed, you need [using runtime transform tool](https://iendeavor.github.io/import-meta-env/guide/getting-started/introduction.html#guide) to do this:

<img width="690" alt="image" src="https://user-images.githubusercontent.com/22850435/208083095-74458a33-6480-4c33-b6bc-41ba338764c3.png">

If you're using `npx vite preview` to serve the dist code, you can run `npx import-meta-env ...` before it:
https://github.com/iendeavor/import-meta-env/blob/main/packages/examples/vite-vue-ts-example/package.json#L8

**Comment by cmcleese** [comment]
I'm using `quasar serve` or `quasar dev` to run the vite server.
I know it third party but I can pass in other vite plugins no problem.
For example: passing in importMeta transformer
```js
vitePlugins: [
        [
          importMetaEnv.vite({
            example: '.env.example',
          }),
        ],
```
But after inspecting from either dev of prod build the `globalThis.import_meta_env` is not being transformed.
I could make a separate repo to showcase.

index.html
![image](https://user-images.githubusercontent.com/2061466/208089450-f0f058c5-93ec-4525-973f-175bac65a4cd.png)

**Comment by cmcleese** [comment]
I removed the imports for `import.meta.env` as suggested and used cypress env variables instead in the `cypress.config.ts`
```js
  env: {
    APP_WEBAPI: process.env.APP_WEBAPI,
    LS_DATA_PREFIX: process.env.LS_DATA_PREFIX,
  },
```

and this appears to work as described. 
Thank you again for the insight and help!

**Comment by iendeavor** [comment]
> I should also point out that in dev mode it doesnt error as it seems the global ref is not needed
> I have no problems in my code using for ex: import.meta.env.APP_WEBAPI without the global ref.

Yes, in the development, the placeholder is not used. I will document it 😅 .

**Comment by cmcleese** [comment]
sorry, i did mean to close with comment as i couldn't still get it to work with build (prod) transform.
I'll try to make a repo or codepen to test and share.

**Comment by cmcleese** [comment]
I later found in my testing that using global import below is not needed for building for production (vite bundling with quasar)
```
<script>
      globalThis.import_meta_env = JSON.parse('"import_meta_env_placeholder"');
</script>
```

I shared a repo for using **quasar** and **import-meta-env**
https://github.com/cmcleese/quasar-import-meta

This is where the importMetaEnv vite config goes: 
https://github.com/cmcleese/quasar-import-meta/blob/master/quasar.config.js#L89

**Comment by iendeavor** [comment]
> I later found in my testing that using global import below is not needed for building for production (vite bundling with quasar)

But this way, the environment variables will be bundled into dist when compiling for production.

You need to adjust your code like this:

Import-meta-env will use 'compile-time' in development, and 'runtime' in production:

```diff
// quasar.config.js
module.exports = configure(function (/* ctx */) {
  return {
    build: {
      vitePlugins: [
        [
          importMetaEnv.vite({
            example: '.env.example',
-           transformMode: 'compile-time',
```

Inject environment variable into dist before serve it:

```diff
// package.json
{
  "scripts": {
-   "serve:prod": "quasar serve ./dist/spa -o -H 127.0.0.1 -p 3000",
+   "serve:prod": "import-meta-env -x .env.example && quasar serve ./dist/spa -o -H 127.0.0.1 -p 3000",
```

```diff
// package.json
{
  "devDependencies": {
+   "@import-meta-env/cli": "^0.4.1"
```

```diff
<!-- index.html -->
<html>
  <body>
+   <script>globalThis.import_meta_env=JSON.parse('"import_meta_env_placeholder"')</script>
    <!-- quasar:entry-point -->
```

**Comment by cmcleese** [comment]
thank for you the clarification. 
I have working this way as well now.
