### ISSUE TITLE
error: unknown option '--path'

### ISSUE THREAD

**Issue by nvonbenken** [iendeavor/import-meta-env#375]
Running `npx import-meta-env -x .env.example.public --path some-path` fails. Same with `-p` instead of `--path`.

**Comment by nvonbenken** [comment]
Missed the recent change to the CLI switching `--output` to `--path` and I had not upgraded yet. Closing this.

**Comment by iendeavor** [comment]
The option `--path` should still works, it is only deprecated. 🤔
