### ISSUE TITLE
Additional flag to not generate warning - The following variables were defined in /app/.env.example.public file but are not defined in the environment

### ISSUE THREAD

**Issue by AdaskoTheBeAsT** [iendeavor/import-meta-env#5]
It would be really amazing if that warning can be made optional by switch - 
it would help in situation when there are plenty of env variables and if given is not found application checks on its own and uses default

**Comment by iendeavor** [comment]
Maybe we can integrate [dotenv-defaults](https://github.com/mrsteele/dotenv-defaults) into this package. 🤔

**Comment by iendeavor** [comment]
Or maybe we can use the .env.meta file to define these metadata:

```ini
# .env.public.example
REQUIRED=
OPTIONAL=
```

```ini
# .env.meta
[optional] # the keys defined under this section will be optional
OPTIONAL=
```

This allows for maximum scalability and flexibility for future implementations such as:

```ini
# .env.meta
[core]
parser=JSON.parse
```

```ini
# .env
REQUIRED=42 # will be parsed to `42` instead of `"42"`
```

**Comment by AdaskoTheBeAsT** [comment]
hmm first idea blocks scenario when defaults in case of non existent env variable will be for example calculated inside of application

idea with meta looks promising

**Comment by AdaskoTheBeAsT** [comment]
after checking thoroughly I changed my mind - indeed that defaults is greater idea

**Comment by iendeavor** [comment]
I found another solution: use [`dotenv-cli`](https://github.com/entropitor/dotenv-cli) to load multiple .env files.

For example, we can load `.env` and `.env.defaults` by:

```sh
> pnpm dotenv -e .env -e .env.defaults -- bash -c './node_modules/.bin/import-meta-env -x .env.example.public'
```

**Comment by iendeavor** [comment]
Another idea from gRPC FieldMask:

```ini
FOO=
BAR=
BAZ=
```

```sh
export REQUIRED_FIELDS=FOO,BAR
# or
export OPTIONAL_FIELDS=BAZ

export FOO=1
export BAR=2
```

**Comment by luca-gr4vy** [comment]
I'd be interested in this, ended up using [`dotenv-cli`](https://github.com/entropitor/dotenv-cli) as suggested to load a base `.env.defaults` file with empty values and override with the `.env` file

**Comment by soc221b** [comment]
I recommend you try the [runtime-env](https://github.com/runtime-env/runtime-env?tab=readme-ov-file#runtime-env), which allows defining required and optional environment variables using JSON-schema.

It is also framework/bundler/dotenv-agnostic.

**Comment by luca-gr4vy** [comment]
Thanks! Anything wrong with using `dotenv-cli` in this case? I've already set up everything with `import-meta-env` and not sure it's worth revamping with `runtime-env` at this point
