### ISSUE TITLE
How to use import-meta-env with @swc/jest?

### ISSUE THREAD

**Issue by daangnDylan** [iendeavor/import-meta-env#646]
in jest with @swc/jest, there is not import.meta.env.
If run import.meta.env code, error throw "SyntaxError: Cannot use 'import.meta' outside a module"

Configuration of official docs is also not work.
<img width="567" alt="image" src="https://user-images.githubusercontent.com/85990727/233001857-9161cf88-d7bc-4f20-b523-9f5dfc5dd53c.png">

I tried to run ignoring this warning but throw new error below
<img width="682" alt="image" src="https://user-images.githubusercontent.com/85990727/233002567-09733074-cca3-4789-9ef0-01dd9f4b2860.png">

I'm using react, @swc/jest, @testing-library/react and vite
How can I setup @swc/jest?

**Comment by iendeavor** [comment]
Hi @daangnDylan 

Could you provide a minimal reproducible repository?
