### ISSUE TITLE
@vue+cli@4 TypeScript "TS2339: Property 'env' does not exist on type 'ImportMeta'."

### ISSUE THREAD

**Issue by swissbuechi** [iendeavor/import-meta-env#8]
I have some troubles to use the Plugin in TypeScript files.

My environment:
Vue: 2.6.14
Vue Cli: 4.5.15

I installed the Plugin using the "@vue+cli@4-example" example guide.

It's working fine in JavaScript files.

Using `import.meta.env.MY_VAR` in .ts files gives me the following IDE error: 

`TS2339: Property 'env' does not exist on type 'ImportMeta'.`

main.ts error log:
```
ERROR in /home/raphi/Repos/netider/knx-shutter-app/src/main.ts(13,33):
13:33 Property 'env' does not exist on type 'ImportMeta'.
    11 | const options: MsalPluginOptions = {
    12 |     clientId: import.meta.env.APP_AAD_CLIENT_ID,
  > 13 |     loginAuthority: import.meta.env.APP_AAD_LOGIN_AUTHORITY,
       |                                 ^
    14 | };
```

Could you maybe provide me with the additional stepps to get it working in .ts files?

Thanks a lot in advance!
PS: I'm really enjoying the plugin so far. Very simple solution for such an annoying thing.

**Comment by swissbuechi** [comment]
I just found this documentation:
https://iendeavor.github.io/import-meta-env/guide.html#intellisense-for-typescript-1

Thanks for your awsome plugin!

I whink you can close this issue.

**Comment by iendeavor** [comment]
Hi 👋 , @swissbuechi 

> import.meta is only allowed when targeting ESNext modules and ECMAScript targets. - https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html#support-for-importmeta


And this is a working example written by webpack+ts-loader: https://github.com/iendeavor/import-meta-env/blob/main/packages/examples/webpack-ts-loader-example/tsconfig.json

Hope this helps~😄

**Comment by iendeavor** [comment]
Since you are using vue-cli, you should use this instead of the Vite's one: https://iendeavor.github.io/import-meta-env/guide.html#intellisense-for-typescript
