### ISSUE TITLE
vite build issue with .env.example

### ISSUE THREAD

**Issue by egaspro** [iendeavor/import-meta-env#857]
Vite.config.js
```
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react-swc";
import importMetaEnv from "@import-meta-env/unplugin";

export default defineConfig({
plugins: [react(), importMetaEnv.vite({ example: ".env.example" })]
});
```
.env and .env.example files are git ignored.

Dockerfile (runtime):
```
...
RUN npm install @import-meta-env/cli
RUN npm install -g serve

ENTRYPOINT ["sh", "entrypoint.sh"]
```

Entrypoint
```
#!/bin/bash
npx import-meta-env -x .env.example -p dist/index.html
serve -s /opt/app-root/src/dist -l 8080
```

.env.example is mounted to runtime container from outside

The issue start with CICD where the setup us: build (ci) once and deploy same image to several environments till production. CI has a challenge where `vite build` requires .env.example file even though it does not use contents of it, CI unit test step also needs atleast empty .env.example file probably because vitest library uses same configuration from vite.config.js.

For now we have this work-around in package.json:
```
"dev": "vite",
"build": "touch .env.example && vite build && rm .env.example",
"test": "vitest",
"test:ci": "touch .env.example && vitest && rm .env.example",
```

But would be nice that .env.example would not be attempted to load in production mode (NODE_ENV) when it's configured to use compile-time. Also a question how to avoid loading this file for unit tests.

**Comment by iendeavor** [comment]
Hi @egaspro,

> .env and .env.example files are git ignored.

.env SHOULD NOT be added to git, but the .env.example file SHOULD be added to the git repository, since the .env.example file does not contain any sensitive information.

> .env.example is mounted to runtime container from outside

No offense intended, could you provide more information on why .env.example needs to be mounted from outside? (If you add .env.example into your git repository maybe this is no longer an issue.)

> CI has a challenge where vite build requires .env.example file even though it does not use contents of it

In Vite, we still need the .env.example file, because users may misuse import-meta-env and Vite's built-in environment variable functionality, we need the .env.example file to provide useful error messages for these users.

Thanks for your feedback. 😄

**Comment by egaspro** [comment]
Hi @iendeavor ,

We have 3 runtime environments: 2 QA ones and Production. Because of that we manage deployment of different features under feature flags in code, where developed code gets deployed but is disabled by feature flag - we often work on different features simultaneously. In that setup is not uncommon to have different amount of environment variables in different environments, meaning differing .env.example files.

On the side note: when testing with .env.example file being commited to git, got an issue with running test with vitest, where env variables were expected to be in process.env already before hitting unit test setup (with .env.example present) - wasn't clear how mocking of env variables should happen there. And we also have limitation that env variables are only injected into runtime environments after CI is done.

**Comment by iendeavor** [comment]
There are two main objectives of the .env.example file:
- to prevent us from forgetting to add the environment variables we need in production.
- to prevent us from exposing sensitive information to client users (i.e., if your .env.example contains a `SECRET_KEY`, import-meta-env will inject the corresponding value to your code even if you aren't using it in your code).

Even though your environments are changed very often, I would still recommend you to check it into your repository too.


In unit testing, for best practices, you should treat the environment variables as external dependencies, and then you will implement dependency inversion for your functions, classes, etc., in this way, you can test it without real environment variables.

**Comment by egaspro** [comment]
Oh i thought is mostly to filter env variables from process.env to not add all of them.

It's easy to keep same env variables when adding new ones, but could get tricky when deleting them - usually that goes with removing deleting some code also and that should be tested, with 1 env variable removed from everywhere and code only just moving through environments - could get tricky with hotfix'es during that time.

With unit test i had different issue, tests themselves work fine with empty .env.example file. Problem is that if .env.example is not empty, running `npm run test` ("test": "vitest") fails immediately with an error that env variables in .env.example were not found. It's an issue in CI pipeline. Locally it works since you can have ignored .env file.
